# Generated by Django 5.2.7 on 2025-11-29 00:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AuditoriaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Nuevo Producto'), ('MODIFICACION', 'Cambio de Precio/Stock'), ('BAJA', 'Eliminado')], max_length=20)),
                ('nombre_producto', models.CharField(max_length=100)),
                ('precio_registrado', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario_cliente', models.CharField(blank=True, max_length=150, null=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('CANCELACION', 'Cancelación')], max_length=20)),
                ('id_reserva_original', models.CharField(max_length=100)),
                ('fecha_reserva', models.DateField(null=True)),
                ('hora_reserva', models.TimeField(null=True)),
                ('numero_personas', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AuditoriaVenta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_accion', models.DateTimeField(auto_now_add=True)),
                ('usuario_responsable', models.CharField(blank=True, help_text='Usuario que realizó la acción', max_length=150, null=True)),
                ('accion', models.CharField(choices=[('CREACION', 'Creación'), ('ACTUALIZACION', 'Actualización'), ('ELIMINACION', 'Eliminación')], max_length=20)),
                ('id_pedido_original', models.CharField(max_length=50)),
                ('total_venta', models.DecimalField(decimal_places=2, max_digits=10)),
                ('estado_venta', models.CharField(max_length=50)),
                ('detalles', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
