# Generated by Django 5.2.7 on 2025-11-14 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mesa',
            name='tipo',
            field=models.CharField(choices=[('NORMAL', 'Normal'), ('PREMIUM', 'Premium (Ventana/Privado)')], default='NORMAL', max_length=10),
        ),
    ]
