# Generated by Django 5.2.7 on 2025-11-04 22:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_prod', models.CharField(max_length=100)),
                ('descripcion_prod', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_prod', models.DecimalField(decimal_places=2, max_digits=10)),
                ('categoria_prod', models.CharField(max_length=50)),
                ('estado_prod', models.CharField(default='disponible', max_length=20)),
                ('cantidad_prod', models.IntegerField(default=0, help_text='Cantidad en inventario')),
            ],
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platillo_menu', models.CharField(max_length=100)),
                ('tipo_menu', models.CharField(max_length=50)),
                ('descripcion_menu', models.CharField(blank=True, max_length=200, null=True)),
                ('estado_menu', models.CharField(default='disponible', max_length=20)),
                ('precio_menu', models.DecimalField(decimal_places=2, max_digits=10)),
                ('productos', models.ManyToManyField(blank=True, help_text='Ingredientes de este platillo', to='productos.producto')),
            ],
        ),
    ]
