<<<<<<< HEAD
# Generated by Django 5.2.7 on 2025-11-06 02:53

=======
# Generated by Django 5.2.7 on 2025-11-04 22:29

import django.db.models.deletion
>>>>>>> origin/Ventas
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
<<<<<<< HEAD
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci_nit', models.CharField(max_length=20, unique=True)),
            ],
        ),
=======
                ('nombre_cliente', models.CharField(max_length=100)),
                ('email_cliente', models.EmailField(max_length=100, unique=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClientesDispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dispos', models.CharField(help_text='ID de dispositivo para notificaciones', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
        migrations.AddField(
            model_name='cliente',
            name='cliente_tipo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientestipo'),
        ),
>>>>>>> origin/Ventas
    ]
