# Generated by Django 5.2.7 on 2025-11-07  (resuelta merge)
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ClientesTipo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_cliente', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('apellido', models.CharField(max_length=100)),
                ('ci_nit', models.CharField(max_length=20, unique=True)),
                ('nombre_cliente', models.CharField(max_length=100, blank=True, null=True)),
                ('email_cliente', models.EmailField(max_length=100, unique=True, blank=True, null=True)),
                ('telefono_cliente', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha_registro', models.DateField(auto_now_add=True, null=True, blank=True)),
                ('cliente_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.clientestipo')),
            ],
        ),
        migrations.CreateModel(
            name='ClientesDispositivos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('num_dispos', models.CharField(help_text='ID de dispositivo para notificaciones', max_length=50)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='clientes.cliente')),
            ],
        ),
    ]