# Generated by Django 5.2.7 on 2025-11-04 22:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('clientes', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EstadosReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_estado', models.CharField(max_length=50)),
                ('descripcion', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_mesas', models.IntegerField(unique=True)),
                ('capacidad_mesas', models.IntegerField()),
                ('estado_mesas', models.CharField(default='disponible', max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateTimeField()),
                ('cliente', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='clientes.cliente')),
                ('estado_reserva', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='reservas.estadosreserva')),
                ('mesas', models.ManyToManyField(to='reservas.mesa')),
            ],
        ),
        migrations.CreateModel(
            name='PoliticaReserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion_politica', models.CharField(max_length=200)),
                ('tiempo_min', models.IntegerField(help_text='Tiempo mínimo de antelación en horas')),
                ('multa_cancelacion', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
                ('reserva', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reservas.reserva')),
            ],
        ),
    ]
