# Generated by Django 5.2.7 on 2025-11-14 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='duracion_horas',
            field=models.IntegerField(default=2, help_text='Duración de la reserva en horas'),
        ),
        migrations.AddField(
            model_name='reserva',
            name='hora_fin',
            field=models.TimeField(blank=True, editable=False, null=True),
        ),
        migrations.AddField(
            model_name='reserva',
            name='monto_pagado',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
