# Generated by Django 5.2.7 on 2025-11-14 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reservas', '0002_reserva_duracion_horas_reserva_hora_fin_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reserva',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
